version: "3.9"
services:
  agentic_orchestrator:
    image: agenticai:latest
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    command: uvicorn agentic_orchestrator_service:app --host 0.0.0.0 --port 8000
    ports:
      - "8223:8000"

  agentic_service:
    image: agenticai:latest
    command: uvicorn agentic_service:app --host 0.0.0.0 --port 8000
    ports:
      - "8222:8000"

  prod_agentic_orchestrator:
    image: agenticai:latest
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8224:8000"